### ISSUE TITLE
mock is required to run test_standalone.py

### ISSUE THREAD

**Issue by m3brown** [cfpb/owning-a-home-api#52]
The `mock` library is required to run the `test_standalone.py` script, but mock is not included in the requirements.txt.

The need to install mock should be either mentioned in the README instructions, included in the `requirements.txt`, or added to something like `requirements-test.txt`

**Comment by amymok** [comment]
@m3brown This has been fixed in https://github.com/cfpb/owning-a-home-api/pull/74

Please let me know if there's any other questions.
