### ISSUE TITLE
Version numbers are inconsistent across Git tags, setup.py, and CHANGELOG.md

### ISSUE THREAD

**Issue by willbarton** [cfpb/owning-a-home-api#53]
[`setup.py`](https://github.com/cfpb/owning-a-home-api/blob/master/setup.py) lists the version number as 1.0. This is the version number that any version specifiers expressed by, say, `pip`, will pay attention to.

There are git tags for versions 0.9.1 through 0.9.6.

The [`CHANGELOG.md`](https://github.com/cfpb/owning-a-home-api/blob/master/CHANGELOG.md) file lists a 0.0.1 version from 2014-11-07 without any particularly interesting information. 

There should probably be some consistency between version numbers.

**Comment by fna** [comment]
https://github.com/cfpb/owning-a-home-api/pull/60
