### ISSUE TITLE
MySQL should not be required to run tests

### ISSUE THREAD

**Issue by m3brown** [cfpb/owning-a-home-api#55]
The `test_standalone.py` script executes tests against a sqlite database.  However, MySQL is required for two reasons:

`MYSQL-python` is listed in the requirements.txt, and this won't install without `mysql_config` installed on the system (e.g. via `brew install mysql`)

The `ratechecker/management/commands/load_daily_data.py` management command imports `_mysql_exceptions`, which causes tests to fail unless the MySQL stack is installed.

**Comment by amymok** [comment]
@m3brown This has been fixed in https://github.com/cfpb/owning-a-home-api/pull/76

Please let me know if there's any other questions.
