### ISSUE TITLE
Provide some sample data for RateChecker

### ISSUE THREAD

**Issue by willbarton** [cfpb/owning-a-home-api#56]
As a new user of the application, I can install the `countylimits` and `ratechecker` apps in a Django project, but there is no sample data or documentation regarding that data's format for the `load_daily_data` management command.

Despite the fact that we explicitly state that the app relies on data that is not available externally, sample data (or possibly test fixtures) would be useful in setting up copy of the `ratechecker` app.

**Comment by fna** [comment]
We are trying to decide wether there's anything in the contract that can stop us from providing even modified data that we obtained. In the mean time there are some clues as to what is expected in the tests:
https://github.com/cfpb/owning-a-home-api/blob/master/ratechecker/tests/test_load_daily_data_command.py#L141
https://github.com/cfpb/owning-a-home-api/blob/master/ratechecker/tests/test_load_daily_data_command.py#L228
