### ISSUE TITLE
django rest framework version

### ISSUE THREAD

**Issue by laminfaty** [cfpb/owning-a-home-api#57]
I know that we are using version 2.4.3 and I am wondering when are we updating to the latest version.

http://www.django-rest-framework.org/topics/3.0-announcement/

**Comment by fna** [comment]
I had problems with it in the past, I can't remember what it was right now. I'll plan some time in the coming month for this upgrade

**Comment by amymok** [comment]
@laminfaty Current version in cf.gov is 2.4.3, so we cannot upgrade unless we also upgrade everything else.
