### ISSUE TITLE
Routing issue with mortgage-insurance API

### ISSUE THREAD

**Issue by lfatty** [cfpb/owning-a-home-api#78]
http://build.consumerfinance.gov/oah-api/mortgage-insurance/%3Cscript%3Ealert%281%29%3C/script%3E?price=520000&loan_amount=500000&minfico=730&maxfico=750&loan_term=30&rate_structure=fixed&loan_type=fixed&loan_type=conf

**Comment by amymok** [comment]
Fixed here: https://github.com/cfpb/owning-a-home-api/pull/83

Let me know if there's still any questions/concerns.

@lfatty
