### ISSUE TITLE
true/false inconsistencies

### ISSUE THREAD

**Issue by cfarm** [cfpb/owning-a-home-api#81]
for the Rate Checker API and Mortgage Insurance there are different values for boolean true/false:

[Rate checker `io` param](https://github.com/cfpb/owning-a-home-api#what-the-app-does)
accepts the following values:
>0 = false,
1 = true,
blank

[Mortgage Insurance `va_first_use` param](https://github.com/cfpb/owning-a-home-api#mortgageinsurance)
accepts 
>Y = Yes
N = No

I recommend we keep them consistent so use what the Rate Checker currently implements (though honestly I'd prefer true/false for both)

**Comment by amymok** [comment]
@cfarm Do you mean you prefer the way for `io` param (0 = false, 1= true) or you want something like true = true, false = false?

**Comment by cfarm** [comment]
the latter: true = true, false = false.

**Comment by cfarm** [comment]
But if we make that change instead of just implementing the 0 = false, 1= true for Mortgage Insurance, we'd have to update rate checker + LC params and tests and I'd rather not :)

**Comment by amymok** [comment]
Okay, I am sticking with 0 = false, 1 = true for now.

**Comment by amymok** [comment]
This is completed in https://github.com/cfpb/owning-a-home-api/pull/82.

Let me know if you still have any questions/concerns.
@cfarm
